Vagrant.configure("2") do |config|

  # Configuration for VM1
  config.vm.define "express_react" do |express_react|
    express_react.vm.box = "ubuntu/bionic64"
	  express_react.vm.network "private_network", ip: "192.168.40.23"
  	express_react.vm.provider "virtualbox" do |vb|
     vb.memory = "1024"
	   vb.cpus = 2
  end

    express_react.vm.provision "shell", inline: <<-SHELL
      sudo apt-get update
      sudo apt-get install software-properties-common -y
      sudo apt-add-repository --yes --update ppa:ansible/ansible
      sudo apt-get install ansible -y
      sudo apt-get install ansible-doc -y
      echo "================ Installing Docker ==================="
      sudo apt-get update
      sudo apt-get install -y apt-transport-https ca-certificates curl software-properties-common
      curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
      sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
      sudo apt-get update
      sudo apt-get install docker-ce -y
      sudo systemctl start docker
      sudo systemctl enable docker
      echo "================ Docker Version ==================="
      docker --version
      echo " ============= Making Vagrant docker user =================="
      sudo usermod -aG docker $(whoami)
      sudo id
      SHELL
    end

end