
Vagrant.configure("2") do |config|

  # VM 1
  config.vm.define "web01" do |web01|
    web01.vm.box = "ubuntu/bionic64"
	  web01.vm.network "private_network", ip: "192.168.40.20"
  	web01.vm.provider "virtualbox" do |vb|
     vb.memory = "1024"
	   vb.cpus = 2
  end

    web01.vm.provision "shell", inline: <<-SHELL
      sudo apt-get update
      echo "===========  DOCKER INSTALLATION STARTED =============="
      sudo apt install apt-transport-https ca-certificates curl software-properties-common
      curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
      sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
      echo "===========  UPDATING SERVICES  =============="
      sudo apt update
      echo "===========  DOCKER CLI INSTALLATION STARTED =============="

      sudo apt install docker-ce docker-ce-cli containerd.io -ylog
      echo "===========  INSTALLATION COMPLETED  =============="
      SHELL
    end

    # VM 2
  
   
end