apiVersion: v1 
kind: Service 
metadata: 
  name: auth-service
spec:
  selector:
    app: auth
  type: ClusterIP # Key diff with LoadBalancer will not be reachable to the outside world. ONLY from inside 
  ports:
  - protocol: TCP
    port: 80 # Outside facing port 
    targetPort: 80 # Internal Pod port of the app 