apiVersion: v1 
kind: Service 
metadata: 
  name: frontend-service
spec:
  selector:
    app: frontend
  type: LoadBalancer # LoadBalancer will  be reachable to the outside world. ONLY from inside 
  ports:
  - protocol: TCP
    port: 80 # Outside facing port 
    targetPort: 80 # Internal Pod port of the app 