apiVersion: v1 
kind: Service 
metadata: 
  name: users-service
spec:
  selector:
    app: users
  type: LoadBalancer
  ports:
  - protocol: TCP
    port: 8080 # outside facing port 
    targetPort: 8080 # internal Pod port of the app 