apiVersion: apps/v1
kind: Deployment
metadata:
  name: users-deployment
spec: 
  replicas: 1
  selector:
    matchLabels:
      app: users
  template:
    metadata:
      labels:
        app: users 
    spec:
      containers:
        - name: users
          image: degreatasaa/kube-demo-users:latest
          env: 
            - name: AUTH_ADDRESS 
              # value: localhost
              # value: "10.104.31.223"
              value: "auth-service.default"

