apiVersion: apps/v1
kind: Deployment 
metadata:
  name: story-deployment
spec: 
  replicas: 2
  selector:
    matchLabels:
      app: story 
  template: 
    metadata:
      labels:
        app: story 
    spec: 
      containers:
        - name: story
          image: degreatasaa/kube-app
          env:
            - name: STORY_FOLDER # must match name defined in app 
              valueFrom:
                configMapKeyRef:
                # name of the metadata in  environment-vars
                  name: data-store-env
                  # key value from the environment-vars
                  key: folder
          volumeMounts:
            - name: story-volume
              mountPath: /app/story
      volumes:
        - name: story-volume
          persistentVolumeClaim:
          # exact name used in the claim definition file resource
            claimName: host-pvc 

          
          