version: "3.8"
services:
  mongodb100:
    image: 'mongo'
    volumes:
      - data:/data/db
      # thats enforcing your custom container name 
    container_name: mongodb100
    env_file:
      - ./env/mongo.env

  backend:
    build: ./backend
    ports: 
      - "88:88"
    volumes:
      - logs:/app/logs # Named volume 
      - ./backend:/app # bind mount 
      - /app/node_modules # anonymous volume 
    env_file:
      - ./env/backend.env
    depends_on:
      - mongodb100


  frontend:
    build: ./frontend
    ports:
      - '3000:3000'
    volumes: 
      - ./frontend/src:/app/src # bind mount 
      # enabling interactive mode for frontend react app.
    stdin_open: true 
    tty: true

    depends_on:
      - backend

# Named Volumes must also be specified here 
volumes:
  data:
  logs: