apiVersion: v1 
kind: Service 
metadata: 
  name: backend
spec:
  selector:
    app: second-app
  ports:
    - protocol: TCP    
      port:  80
      targetPort: 8080
    # - protocol: TCP
    #   port: 443
    #   targetPort: 443
    # ClusterIP: default and internally exposed IP, accessible from inside the cluster ONLY

    # NodePort expose the IP and Port of the worker the node 
    # LoadBalancer exposed ports to the outside world 
  type: LoadBalancer